on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths-ignore:
      - '.github/workflows/semgrep_manual.yml'
      - '.github/workflows/deploy.yml'
      - 'rules'
      - '.detaignore'
      - '.gitignore'
      - 'README.md'

name: Semgrep for Pull Requests and Push events
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
        publishDeployment: 2420
