name: Semgrep

on: workflow_dispatch

jobs:
  semgrep:
    name: Semgrep Manual Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          auditOn: push
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 2420
